import Head from "next/head";
import { ColorModeScript } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode="light" />
      <main></main>

      <footer></footer>
    </div>
  );
}
