name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          command_timeout: 600m
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd gpt-article
            git pull origin main
            npm install
            npm run build
            pm2 restart all
