name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SERVER_USERNAME }}
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          command_timeout: 600m
          key: ${{ secrets.SERVER_KEY }}
          script: |
            cd gpt-article
            git pull origin main
            npm install
            npm run build
            cd ../
            pm2 stop all
            pm2 delete all
            rm -rf run-old
            mv run run-old
            cp -r gpt-article/ run/
            cd run
            pm2 start "npm run start" --name "gpt-article"
